import { Route } from "../domain/types";
import { LoginPage, NotFound, ProfilePage, ResetEmail } from "../pages";
import { IoMdCalendar } from "react-icons/io";
import {
  MdChat,
  MdCheck,
  MdNotifications,
  MdPerson,
  MdPersonAdd,
  MdSwapVert,
} from "react-icons/md";

const routes: Route[] = [
  {
    path: "*",
    title: "404",
    element: <NotFound />,
    isProtected: false,
    useDefaultLayout: false,
    showOnMenu: false,
  },
  {
    path: "/",
    title: "Login",
    element: <LoginPage />,
    isProtected: false,
    useDefaultLayout: false,
    showOnMenu: false,
  },
  {
    path: "/login",
    title: "Login",
    element: <LoginPage />,
    isProtected: false,
    useDefaultLayout: false,
    showOnMenu: false,
  },
  {
    path: "/profile",
    title: "Perfil",
    element: <ProfilePage />,
    isProtected: true,
    allowedRoles: "all",
    useDefaultLayout: true,
    showOnMenu: false,
  },
  {
    path: "/settings",
    title: "Configurações",
    element: <div>Configurações</div>,
    isProtected: true,
    allowedRoles: "all",
    useDefaultLayout: true,
    showOnMenu: false,
  },
  {
    path: "/help",
    title: "Ajuda",
    element: <div>Ajuda</div>,
    isProtected: true,
    allowedRoles: "all",
    useDefaultLayout: true,
    showOnMenu: false,
  },
  {
    path: "/calendar",
    title: "Calendário",
    element: <div>Calendar</div>,
    isProtected: true,
    allowedRoles: ["medic"],
    useDefaultLayout: true,
    showOnMenu: true,
    icon: <IoMdCalendar />,
  },
  {
    path: "/swap-request",
    title: "Solicitação de troca",
    element: <div>Solicitação de troca</div>,
    isProtected: true,
    allowedRoles: ["medic"],
    useDefaultLayout: true,
    showOnMenu: true,
    icon: <MdSwapVert />,
  },
  {
    path: "/chat",
    title: "Chat",
    element: <div>Chat</div>,
    isProtected: true,
    allowedRoles: ["medic"],
    useDefaultLayout: true,
    showOnMenu: true,
    icon: <MdChat />,
  },
  {
    path: "/general-calendar",
    title: "Calendário",
    element: <div>Calendar</div>,
    isProtected: true,
    allowedRoles: ["moderator"],
    useDefaultLayout: true,
    showOnMenu: true,
    icon: <IoMdCalendar />,
  },
  {
    path: "/users",
    title: "Usuários",
    element: <div>Usuários</div>,
    isProtected: true,
    allowedRoles: ["moderator"],
    useDefaultLayout: true,
    showOnMenu: true,
    icon: <MdPerson />,
  },
  {
    path: "/user-register",
    title: "Cadastro",
    element: <div>Cadastro</div>,
    isProtected: true,
    allowedRoles: ["moderator"],
    useDefaultLayout: true,
    showOnMenu: true,
    icon: <MdPersonAdd />,
  },
  {
    path: "/attendance",
    title: "Presença",
    element: <div>Presença</div>,
    isProtected: true,
    allowedRoles: "all",
    useDefaultLayout: true,
    showOnMenu: true,
    icon: <MdCheck />,
  },
  {
    path: "/notifications",
    title: "Notificações",
    element: <div>Notificações</div>,
    isProtected: true,
    allowedRoles: "all",
    useDefaultLayout: true,
    showOnMenu: true,
    icon: <MdNotifications />,
  },
  {
    path: "/reset-email/:token",
    title: "Confirmação do e-mail",
    element: <ResetEmail />,
    isProtected: false,
    useDefaultLayout: false,
    showOnMenu: false,
  },
];

export default routes;
